version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_octane_vue
    user: "${UID}:${GID}"
    environment:
      - PHP_SERVER=${PHP_SERVER:-octane}
    volumes:
      - ./src:/var/www
    ports:
      - "${APP_PORT:-8000}:8000"
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - laravel_octane_vue_network-2

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel_octane_vue_network-2
    profiles:
      - fpm

  db:
    image: mysql:8.0
    container_name: laravel_octane_vue_db
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel_octane_vue_network-2

  node:
    image: node:20
    container_name: laravel_octane_vue_node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel_octane_vue_network-2
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel_octane_vue_network-2
  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_queue
    user: "${UID}:${GID}"
    volumes:
      - ./src:/var/www
      - ./docker/php/queue-start.sh:/queue-start.sh
    command: sh /queue-start.sh
    depends_on:
      - redis
      - db
    entrypoint: []
    networks:
      - laravel_octane_vue_network-2

networks:
  laravel_octane_vue_network-2:


volumes:
  db_data:
